eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

server:
  port: 8500
spring:
  application:
    name: app-huakai-pay
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3340/huakai_pay
    username: root
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999